# docker-compose -f .\docker-compose.yml -f .\docker-compose-sp.yml up -d
# docker-compose -f .\docker-compose.yml -f .\docker-compose-sp.yml ps
# docker-compose -f .\docker-compose.yml -f .\docker-compose-sp.yml down

version: '3.5'
networks:
  default:
    name: kafka-platform
services:
  tracabgen5filter:
    image: tracabgen5filter:latest
    hostname: tracabgen5filter
    container_name: tracabgen5filter
    ports:
      - 8180:8080
    depends_on:
        - kafka-1
        - kafka-2
        - kafka-3
        - schema-registry-1
  tracabgen5enricher:
    image: tracabgen5enricher:latest
    hostname: tracabgen5enricher
    container_name: tracabgen5enricher
    ports:
      - 8181:8080
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry-1
  tracabgen5spliter:
    image: tracabgen5spliter:latest
    hostname: tracabgen5spliter
    container_name: tracabgen5spliter
    ports:
      - 8182:8080
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry-1
  general-worker-acceleration:
    image: general-worker-acceleration:latest
    hostname: general-worker-acceleration
    container_name: general-worker-acceleration
    ports:
      - 8183:8080
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry-1
  general-worker-ball-zone-change:
    image: general-worker-ball-zone-change:latest
    hostname: general-worker-ball-zone-change
    container_name: general-worker-ball-zone-change
    ports:
      - 8184:8080
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry-1
  general-worker-ball-possession-change:
    image: general-worker-ball-possession-change:latest
    hostname: general-worker-ball-possession-change
    container_name: general-worker-ball-possession-change
    ports:
      - 8185:8080
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry-1
